### ISSUE TITLE
Attachments not being added to email

### ISSUE THREAD

**Issue by stuartcusackie** [aerni/statamic-livewire-forms#14]
I have enabled the 'Attach uploaded assets to this email.' toggle on the statamic form but it seems that no attachment is being added.

I'm testing this with Mailtrap so the attachment might be hidden somewhere, but I cannot see it anywhere in the raw version of the email.

Does this work or am I doing something wrong? Thanks.

**Comment by aerni** [comment]
I'm not sure if this is an issue with this addon or with Statamic. This addon doesn't do anything special. It simply triggers Statamic's email job. I'll have a look at it.

**Comment by aerni** [comment]
Did you try with a regular Statamic form without this addon? Do the attachments work as expected?

**Comment by stuartcusackie** [comment]
I just tried to do this now but it seems the form tag is unusable with blade at the moment: https://github.com/statamic/cms/issues/5534

**Comment by aerni** [comment]
If you use Blade, simply import an Antlers partial that includes the form tag. This way you should be able to test it.

**Comment by stuartcusackie** [comment]
> simply import an Antlers partial
I did not know that was possible. Nice! 

So I have run a full antlers / regular Statamic form test and the file attached correctly. I'm pretty sure it is a problem with this package. I made some checks to be sure:

- I have compared the forms settings and blueprint to make sure there are no configuration differences.
- I have tried the same form using antlers only VS using this package. The file attached to the basic form, whereas it did not attach to this package's form.

**Comment by aerni** [comment]
Hmm, that's odd. Using this addon, was the file actually uploaded and added to the form submission? If not, that would explain why it's not attached to the email either.

**Comment by stuartcusackie** [comment]
It was indeed. I can see the file in control panel but not on the email.

**Comment by aerni** [comment]
What versions are you on? Please run `php please support:details` and post the output here.

**Comment by stuartcusackie** [comment]
Statamic 3.3.11 Pro
Laravel 9.12.2
PHP 8.1.1
aerni/livewire-forms 3.2.0
jonassiewertsen/statamic-livewire 2.9.0
rias/statamic-redirect 2.2.0
spatie/statamic-responsive-images 2.11.2
statamic/seo-pro 3.1.0

**Comment by aerni** [comment]
Ok, I think I narrowed this down after some testing. I couldn't get attachments working with Statamic's form tag either. I then came across this issue: https://github.com/statamic/cms/issues/6057. After setting `max_files: 1` in the form blueprint, the attachment worked. Both with the form tag and Livewire Forms. 

Please check if attachments work when setting `max_files: 1` in your form blueprint.

**Comment by stuartcusackie** [comment]
I actually have max_files: 1 set already so there' something else going on. Here's the full file field definition:

```
-
        handle: cv_file
        field:
          mode: list
          container: cvs
          restrict: false
          allow_uploads: true
          show_filename: true
          max_files: 1
          display: 'Upload Your CV'
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          read_only: false
          validate:
            - required
```

I did stumble into another problem when testing with with regular antlers forms. There's a [bug](https://github.com/statamic/cms/issues/5933) with multiple asset containers and forms, but I've tried deleting my additional container and still the file is not attaching. 

I don't have any more clues right now...

**Comment by aerni** [comment]
Did you upgrade to Statamic 3.3.12 already? The bug you linked should be fixed now. 

I suggest you start from a fresh installation and start adding things until the bug happens again. At that point, you'll have a clearer idea of what's causing this issue. If you can reproduce it, feel free to share the repo along with a detailed description how to reproduce this bug.

**Comment by stuartcusackie** [comment]
I just tried 3.3.12 and there's no difference.

I have put together a fresh install with just the basics and the problem still persists. I have added every step that I took to the README.md:
https://github.com/stuartcusackie/lformtest

**Comment by stuartcusackie** [comment]
Awesome, thanks. No rush on my end. This project won't be ready for a while.
